### ISSUE TITLE
Should you remove the node_modules folder?

### ISSUE THREAD

**Issue by joaomatossilva** [nmcc/actions-gitversion#1]
is it necessary to have the node_modules committed? shouldn't it be "downloaded" on demand with `npm install`?

Because some of those packages may be compiled based on the target computer.

Or is it a requirement to run inside a github action...

**Comment by nmcc** [comment]
From [GitHub's documentation](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-a-javascript-action#commit-and-push-your-action-to-github), it is necessary to commit the `node_modules` directory.

Transcript:
>From your terminal, commit your `action.yml`, `index.js`, `node_modules`, `package.json`, `package-lock.json`, and `README.md` files. If you added a `.gitignore` file that lists `node_modules`, you'll need to remove that line to commit the `node_modules` directory.
